<?php
namespace setbased\Stratum;

/**
 * Class for holding all constants generated by PhpStratum.
 */
class C
{
  /**
   * @setbased.stratum.constants
   *
   * Below this doc block constants will be inserted by PhpStratum.
   */
  const TST_ID_BUNNY    = 3;
  const TST_ID_CAT      = 4;
  const TST_ID_EGGS     = 2;
  const TST_ID_ELEPHANT = 5;
  const TST_ID_SPAM     = 1;
}