/** Test for desgination type row0.
    @param p_count The number of rows selected.
                   * 0 For a valid test.
                   * 1 For a valid test.
                   * 2 For a invalid test.
 */
create procedure tst_test_row0a_with_lob( p_count int,
                                          p_blob  blob )
reads sql data
-- type: row0
begin
  select *
  from   TST_FOO2
  where  tst_c00 <= p_count
  ;
end
