/** Test for all possible types of arguments without LOB's.
 */
create procedure tst_test01( p_param00 @tst_foo1.tst_c00%type@,
                             p_param01 @tst_foo1.tst_c01%type@,
                             p_param02 @tst_foo1.tst_c02%type@,
                             p_param03 @tst_foo1.tst_c03%type@,
                             p_param04 @tst_foo1.tst_c04%type@,
                             p_param05 @tst_foo1.tst_c05%type@,
                             p_param06 @tst_foo1.tst_c06%type@,
                             p_param07 @tst_foo1.tst_c07%type@,
                             p_param08 @tst_foo1.tst_c08%type@,
                             p_param09 @tst_foo1.tst_c09%type@,
                             p_param10 @tst_foo1.tst_c10%type@,
                             p_param11 @tst_foo1.tst_c11%type@,
                             p_param12 @tst_foo1.tst_c12%type@,
                             p_param13 @tst_foo1.tst_c13%type@,
                             p_param14 @tst_foo1.tst_c14%type@,
                             p_param15 @tst_foo1.tst_c15%type@,
                             p_param16 @tst_foo1.tst_c16%type@,
                             p_param17 @tst_foo1.tst_c17%type@,
                             p_param26 @tst_foo1.tst_c26%type@,
                             p_param27 @tst_foo1.tst_c27%type@ )
reads sql data
-- type: none
begin
end
