/**
 * Test for designation type singleton1 with BLOB.
 *
 * @param p_count The number of rows selected.
 *                * 0 For a invalid test.
 *                * 1 For a valid test.
 *                * 2 For a invalid test.
 * @param p_value The selected value.
 * @param p_blob  The BLOB.
 */
create procedure tst_test_singleton1b_with_lob(p_count int, p_value int, p_blob blob)
reads sql data
-- type:   singleton1
-- return: bool
begin
  select p_value
  from   TST_FOO2
  where  tst_c00 <= p_count
  ;
end
