/**
 * Test for conversion of MySQL types to PHP types.
 *
 * @param p_php_type1 Must be converted to PHP type string in the TestDataLayer.
 * @param p_php_type2 Must be converted to PHP type string in the TestDataLayer.
 */
create procedure tst_test_parameter_type(p_php_type1 decimal(10,2),
                                         p_php_type2 decimal(65,0))
reads sql data
-- type: none
begin
  -- Nothing to do.
end
