/**
 * Test for designation type singleton1 with return type bool.
 *
 * @param p_count The number of rows selected.
 *                * 0 For a invalid test.
 *                * 1 For a valid test.
 *                * 2 For a invalid test.
 * @param p_value The selected value.
 */
create procedure tst_test_singleton1b(p_count int, p_value int)
reads sql data
-- type:   singleton1
-- return: bool
begin
  select p_value
  from   TST_FOO2
  where  tst_c00 <= p_count
  ;
end
