/**
 * Test for all possible types of parameters including LOB's.
 *
 * @param p_tst_int        Parameter of type int.
 * @param p_tst_smallint   Parameter of type smallint.
 * @param p_tst_tinyint    Parameter of type tinyint.
 * @param p_tst_mediumint  Parameter of type mediumint.
 * @param p_tst_bigint     Parameter of type bigint.
 * @param p_tst_decimal    Parameter of type decimal.
 * @param p_tst_decimal0   Parameter of type decimal with 0 scale.
 * @param p_tst_float      Parameter of type float.
 * @param p_tst_double     Parameter of type double.
 * @param p_tst_bit        Parameter of type bit.
 * @param p_tst_date       Parameter of type date.
 * @param p_tst_datetime   Parameter of type datetime.
 * @param p_tst_timestamp  Parameter of type timestamp.
 * @param p_tst_time       Parameter of type time.
 * @param p_tst_year       Parameter of type year.
 * @param p_tst_char       Parameter of type char.
 * @param p_tst_varchar    Parameter of type varchar.
 * @param p_tst_binary     Parameter of type binary.
 * @param p_tst_varbinary  Parameter of type varbinary.
 * @param p_tst_tinyblob   Parameter of type tinyblob.
 * @param p_tst_blob       Parameter of type blob.
 * @param p_tst_mediumblob Parameter of type mediumblob.
 * @param p_tst_longblob   Parameter of type longblob.
 * @param p_tst_tinytext   Parameter of type tinytext.
 * @param p_tst_text       Parameter of type text.
 * @param p_tst_mediumtext Parameter of type mediumtext.
 * @param p_tst_longtext   Parameter of type longtext.
 * @param p_tst_enum       Parameter of type enum.
 * @param p_tst_set        Parameter of type set.
 */
create procedure tst_test02( p_tst_int        @tst_foo1.tst_int%type@,
                             p_tst_smallint   @tst_foo1.tst_smallint%type@,
                             p_tst_tinyint    @tst_foo1.tst_tinyint%type@,
                             p_tst_mediumint  @tst_foo1.tst_mediumint%type@,
                             p_tst_bigint     @tst_foo1.tst_bigint%type@,
                             p_tst_decimal    @tst_foo1.tst_decimal%type@,
                             p_tst_decimal0   @tst_foo1.tst_decimal0%type@,
                             p_tst_float      @tst_foo1.tst_float%type@,
                             p_tst_double     @tst_foo1.tst_double%type@,
                             p_tst_bit        @tst_foo1.tst_bit%type@,
                             p_tst_date       @tst_foo1.tst_date%type@,
                             p_tst_datetime   @tst_foo1.tst_datetime%type@,
                             p_tst_timestamp  @tst_foo1.tst_timestamp%type@,
                             p_tst_time       @tst_foo1.tst_time%type@,
                             p_tst_year       @tst_foo1.tst_year%type@,
                             p_tst_char       @tst_foo1.tst_char%type@,
                             p_tst_varchar    @tst_foo1.tst_varchar%type@,
                             p_tst_binary     @tst_foo1.tst_binary%type@,
                             p_tst_varbinary  @tst_foo1.tst_varbinary%type@,                             
                             p_tst_tinyblob   @tst_foo1.tst_tinyblob%type@,
                             p_tst_blob       @tst_foo1.tst_blob%type@,
                             p_tst_mediumblob @tst_foo1.tst_mediumblob%type@,
                             p_tst_longblob   @tst_foo1.tst_longblob%type@,
                             p_tst_tinytext   @tst_foo1.tst_tinytext%type@,
                             p_tst_text       @tst_foo1.tst_text%type@,
                             p_tst_mediumtext @tst_foo1.tst_mediumtext%type@,
                             p_tst_longtext   @tst_foo1.tst_longtext%type@,                             
                             p_tst_enum       @tst_foo1.tst_enum%type@,
                             p_tst_set        @tst_foo1.tst_set%type@ )
reads sql data
-- type: none
begin
  insert into TST_FOO1( tst_int      
  ,                     tst_smallint 
  ,                     tst_tinyint  
  ,                     tst_mediumint
  ,                     tst_bigint   
  ,                     tst_decimal  
  ,                     tst_decimal0 
  ,                     tst_float    
  ,                     tst_double   
  ,                     tst_bit      
  ,                     tst_date     
  ,                     tst_datetime 
  ,                     tst_timestamp
  ,                     tst_time     
  ,                     tst_year     
  ,                     tst_char     
  ,                     tst_varchar  
  ,                     tst_binary   
  ,                     tst_varbinary
  ,                     tst_tinyblob
  ,                     tst_blob
  ,                     tst_mediumblob
  ,                     tst_longblob
  ,                     tst_tinytext
  ,                     tst_text
  ,                     tst_mediumtext
  ,                     tst_longtext
  ,                     tst_enum
  ,                     tst_set )
  values( p_tst_int      
  ,       p_tst_smallint 
  ,       p_tst_tinyint  
  ,       p_tst_mediumint
  ,       p_tst_bigint   
  ,       p_tst_decimal  
  ,       p_tst_decimal0 
  ,       p_tst_float    
  ,       p_tst_double   
  ,       p_tst_bit      
  ,       p_tst_date     
  ,       p_tst_datetime 
  ,       p_tst_timestamp
  ,       p_tst_time     
  ,       p_tst_year     
  ,       p_tst_char     
  ,       p_tst_varchar  
  ,       p_tst_binary   
  ,       p_tst_varbinary
  ,       p_tst_tinyblob
  ,       p_tst_blob
  ,       p_tst_mediumblob
  ,       p_tst_longblob
  ,       p_tst_tinytext
  ,       p_tst_text
  ,       p_tst_mediumtext
  ,       p_tst_longtext
  ,       p_tst_enum
  ,       p_tst_set )
  ;
end
