/**
 *  Test for designation bulk_insert.
 */
create procedure tst_test_bulk_insert01()
modifies sql data
-- type: bulk_insert TST_TEMPO field_int,field_smallint,field_mediumint,field_tinyint,field_bigint,field_int_unsigned,field_smallint_unsigned,field_mediumint_unsigned,field_tinyint_unsigned,field_bigint_unsigned,field_year,field_decimal,field_decimal0,field_float,field_double,field_binary,field_varbinary,field_char,field_varchar,field_time,field_timestamp,field_date,field_datetime,field_enum,field_set,field_bit
begin
  drop temporary table if exists TST_TEMPO;

  create temporary table TST_TEMPO
  (
     tst_int                int,
     tst_smallint           smallint,
     tst_mediumint          mediumint,
     tst_tinyint            tinyint,
     tst_bigint             bigint,
     tst_int_unsigned       int unsigned,
     tst_smallint_unsigned  smallint unsigned,
     tst_mediumint_unsigned mediumint unsigned,
     tst_tinyint_unsigned   tinyint unsigned,
     tst_bigint_unsigned    bigint unsigned,
     tst_year               year,
     tst_decimal            decimal(10,2),
     tst_decimal0           decimal(65),
     tst_float              float,
     tst_double             double,
     tst_binary             binary(10),
     tst_varbinary          varbinary(10),
     tst_char               char(10),
     tst_varchar            varchar(80),
     tst_time               time,
     tst_timestamp          timestamp,
     tst_date               date,
     tst_datetime           datetime,
     tst_enum               enum('a','b','c'),
     tst_set                set('a','b','c'),
     tst_bit                bit(4),
     primary key (tst_int)
  ) engine = memory
  ;
end
